services:
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-db:/data/db
      - mongo-config:/data/configdb
    networks:
      - mongo

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
    networks:
      - mongo-express
      - mongo

  tg-bot:
    build: .
    container_name: tg-bot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mongo

    networks:
      - tg-bot

volumes:
  mongo-db:
    name: mongo-db
  mongo-config:
    name: mongo-config

networks:
  mongo:
    name: mongo
    internal: true
  mongo-express:
    name: mongo-express
  tg-bot:
    name: tg-bot
