name: pre-commit-ci auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'pre-commit-ci[bot]'
    steps:
      - name: Enable auto-merge for pre-commit-ci PRs
        run: gh pr merge --auto --squash --delete-branch "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
